### ISSUE TITLE
products component

### ISSUE THREAD

**Issue by puddlejumper26** [puddlejumper26/xiangs#6]
Because of the settings of Angular Material, and the application of MatSidenavModule, the css styles and template of the `sidebar` are in the Products component

**Comment by puddlejumper26** [comment]
## Html
``` html 

<mat-sidenav-container>
  
  <mat-sidenav #sideNav mode="over" >
    <app-sidebar></app-sidebar>
    <button mat-button (click)="sideNav.close()">CLOSE</button>
  </mat-sidenav>

  <mat-sidenav-content>
      <button mat-button (click)="sideNav.open()">三</button>
  </mat-sidenav-content>
   
</mat-sidenav-container>
```

## Scss
```css
mat-sidenav-container {
  height: 900px;
  width: 100%;
  background-color: lightgrey;
}

mat-sidenav {
    position: absolute;
    width: 150px;
}
```

## component.ts
```ts
import { MatSidenav, MatDrawerMode } from '@angular/material/sidenav';
```

**Comment by puddlejumper26** [comment]
## Html
```html
<mat-sidenav-container>
  <mat-sidenav #sideNav mode="over">
    <app-sidebar></app-sidebar>
  </mat-sidenav>

  <mat-sidenav-content>
    <button id="open-button" mat-button (click)="sideNav.open()">三</button>
    <app-home></app-home>
  </mat-sidenav-content>
</mat-sidenav-container>
```

## Scss
```css
mat-sidenav-container {
  background-color: lightgrey;
  height: 600px;
  width: 100%;
}

mat-sidenav-content {
  position: absolute;   // in order to make the button out of flow
}

mat-sidenav {
  background: black;
  opacity: 0.3;
  position: absolute;
  width: 150px;
}

button {
  color: white;
  background: black;
  opacity: 0.6;
  position: absolute; //// in order to make the button out of flow
}
```

**Comment by puddlejumper26** [comment]
## HTML
```html
<mat-sidenav-container>
  <mat-sidenav #sideNav mode="over">
    <app-sidebar></app-sidebar>
  </mat-sidenav>

  <mat-sidenav-content>
    <button mat-button (click)="sideNav.open()">三</button>
    <div class="website-name">Xiang's Home</div>
    <app-home></app-home>
  </mat-sidenav-content>
</mat-sidenav-container>
```

## SCSS
```scss
mat-sidenav-container {
  background-color: lightgrey;
  height: 600px;
  width: 100%;
}

mat-sidenav-content {
  position: absolute; // in order to make the button  and div out of flow
}

mat-sidenav {
  background: black;
  opacity: 0.6;
  position: absolute;
  width: 150px;
}

button {
  color: white;
  background: black;
  opacity: 0.6;
  position: absolute; // in order to make the button out of flow
}

div.website-name {
  border-radius: 10px;
  color: whitesmoke;
  font-size: 50px;
  left: 500px;
  position: absolute; // in order to make the div out of flow
  text-align: center;
  text-shadow: 1px 1px black, 2px 2px black, 3px 3px black, 4px 4px black;
  top: 50px;
}
```

**Comment by puddlejumper26** [comment]
Mainly to add the **`customClick`** from the **`EventEmitter`** of the **`sidebarComponent`** 

- - - 

## HTML
```html
<mat-sidenav-container>
  <mat-sidenav #sideNav mode="over">
    <app-sidebar (customClick)="sideNav.close()"></app-sidebar>
  </mat-sidenav>

  <mat-sidenav-content>
    <button mat-button (click)="sideNav.open()">三</button>
    <div class="website-name">Xiang's Home</div>
    <router-outlet></router-outlet>
  </mat-sidenav-content>
</mat-sidenav-container>
```

**Comment by puddlejumper26** [comment]
## SCSS 
in order to minimize the code, this time is focusing on the settings of height and width, try to use the nature of element it self, rather than setting numbers. 

```scss
mat-sidenav-container {
  background-image: url(./../../assets/universe7.gif);
  background-repeat:no-repeat;
  background-size:100%;
  height: 100%;
  position: fixed;
  width: 100%;
}

mat-sidenav-content {
  position: absolute; // in order to make the button out of flow
  width: 100%;// to make the other component stay in the center
}

mat-sidenav {
  background: black;
  opacity: 0.6;
  position: absolute;
  width: 150px;
}

button {
  color: white;
  background: black;
  opacity: 0.6;
  position: fixed; // in order to make the button out of flow
  z-index: 99;
}
```
