### ISSUE TITLE
home component

### ISSUE THREAD

**Issue by puddlejumper26** [puddlejumper26/xiangs#7]
This is the default page when opening this website, should contain a fullscreen picture with animations, e.g. waves. 

This part should only contain the animation background,

- Source
-- wallpaper engine

**Comment by puddlejumper26** [comment]
## html
```html
<div class="home">
    <video autoplay loop >
        <source src="../../../assets/ranbing.mp4" type="video/mp4">
    </video>
</div>
```

## scss
```scss
.home {
    background-color:gray;
    background:url(../../../assets/ranbing.mp4) no-repeat center 0px;
}

video {
    right: 0; bottom: 0;
    min-width: 100%; min-height: 100%;
    width: auto; height: 750px; z-index: -100;
    background-size: cover;
}
```

**Comment by puddlejumper26** [comment]
## SCSS 
in order to minimize the code, this time is focusing on the settings of height and width, try to use the nature of element it self, rather than setting numbers. 

```scss
html, body {
  height: 100%;
}

.home {
  background-color: gray;
  background: url(../../../assets/ranbing.mp4) no-repeat center 0px;
}

video {
  right: 0;
  bottom: 0;
  min-width: 100%;
  min-height: 100%;
  width: 100%;
  z-index: -100;
  background-size: cover;
}

div.website-name {
  color: whitesmoke;
  font-size: 50px;
  left: 570px;
  position: absolute; // in order to make the div out of flow
  text-shadow: 1px 1px black, 2px 2px black, 3px 3px black, 4px 4px black;
  top: 45px;
}
```
