### ISSUE TITLE
about component

### ISSUE THREAD

**Issue by puddlejumper26** [puddlejumper26/xiangs#8]
This part is basically the background information of myself

## Detailed contents
- photo
- background introduction
- link to CV (https://puddlejumper26.github.io/js-showcases/resources/personaldoc/CV-XiangWU-de.pdf)
- link to linkedIn
- link to github account
- 10 Miscrosoft certificates??
- comments module (?)

## Angular Material
- basic chips
- flex-layout (responsive)

## Design

![image](https://user-images.githubusercontent.com/40550117/83006806-535cce00-a045-11ea-8bc4-4e3834a4d4af.png)

**Comment by puddlejumper26** [comment]
## html
- fxLayout
- fxFlex
- fxLayout.xs
```html
<div class="about-section" fxLayout="column">
  <div fxFlex="20" fxLayout="row" fxLayout.xs="column">
    <div fxFlex="30" class="photo">
      <img src="../../../assets/photo.jpg" alt="photo" />
    </div>
    <div fxFlex="70">
      <div class="titile">
        <br /><br />
        <h3>Front End Developer</h3>

        <span style="font-weight: 900; color: black;">Email: </span>
        xiang.wu@hotmail.de
        <br /><br />
        <span style="font-weight: 900; color: black;">Favourite:</span>
        Angular, Typescript, Angular Material, JS, HTML, CSS, Git, Bootstrap
        <br /><br />
        <span style="font-weight: 900; color: black;">IDEs:</span> VSC,
        IntelliJI
      </div>
    </div>
  </div>
  <div fxFlex="80">
    <p class="lead">
      I am <b>Puddlejumper26 ( xiang )</b>, I am an enthusiastic and passionate front end
      developer.Front-End rocks!
      <br /><br />
      I graduated from TU Munich(Technische Universität München) in 2013 with a
      Master degree. My master thesis was focusing on the professional
      industrial software (Gabi 6.0 and Cambridge Eco Audit Selector 2013)
      research for industrial products (woods and steel) and their entire life
      cycle.
      <br /><br />
      Since 07/2018 I started to focus on the Front End development, and really
      enjoy the work, it rocks! Between 11/2018-04/2019 I was enrolled in the
      <a
        href="https://academy.microsoft.com/en-us/professional-program/tracks/front-end-development/"
        target="_blank"
        >Microsoft Professional Program for Front-End Web Development</a
      >. <br /><br />
      Since 09/2019, I started to work as <b>Junior Front End Developer</b> in
      Wagawin GmbH. Thanks for my friendly colloagues, I have learned a lot of
      solid knowledge and skills there, very enjoyable!
      <br /><br />
      My personal goal is to become a professional in Full Stack mainly with
      focus on Front End in the next few years.Technique is and will be my
      lifelong pursuit goal.
    </p>

    <div class="certificate">
      <h2>Microsoft Certificate</h2>
      <ul>
        <li>
          <a
            class="list-group-item list-group-item-action"
            href="https://courses.edx.org/certificates/47cd8785c5b942408d1ef3978aafe3c1"
            target="_blank"
            >Verified Certificate of Advanced Angular - Microsoft, edX - 2019
          </a>
        </li>
        <li>
          <a
            class="list-group-item list-group-item-action"
            href="https://courses.edx.org/certificates/42ccb23e11864ef4abffa34354c6e926"
            target="_blank"
            >Verified Certificate of Angular Fundamentals - Microsoft, edX -
            2019
          </a>
        </li>
        <li>
          <a
            class="list-group-item list-group-item-action"
            href="https://courses.edx.org/certificates/4c67f74df3a44eada5a1293e5ef581d4"
            target="_blank"
            >Verified Certificate of Front End Development - Microsoft, edX -
            2018
          </a>
        </li>
        <li>
          <a
            class="list-group-item list-group-item-action"
            href="https://courses.edx.org/certificates/c51bc2253ebf4a5cb42746bc7a6e9d37"
            target="_blank"
            >Verified Certificate of Introduction to TypeScript 2 - Microsoft,
            edX - 2019
          </a>
        </li>
        <li>
          <a
            class="list-group-item list-group-item-action"
            href="https://courses.edx.org/certificates/7e85501625914c6bbc8d719a0a631e5d"
            target="_blank"
            >Verified Certificate of Advanced CSS Concepts - Microsoft, edX -
            2019
          </a>
        </li>
        <li>
          <a
            class="list-group-item list-group-item-action"
            href="https://courses.edx.org/certificates/6d7ee24306094092958887c697b580cc"
            target="_blank"
            >Verified Certificate of Introduction to jQuery - Microsoft, edX -
            2019
          </a>
        </li>
        <li>
          <a
            class="list-group-item list-group-item-action"
            href="https://courses.edx.org/certificates/f49a09f635a44690afb354dc1069cae4"
            target="_blank"
            >Verified Certificate of Introduction to Bootstrap - Microsoft, edX
            - 2019
          </a>
        </li>
        <li>
          <a
            class="list-group-item list-group-item-action"
            href="https://courses.edx.org/certificates/64221ebe413642149443af36dcc80b79"
            target="_blank"
            >Verified Certificate of JavaScript Introduction- W3C, edX - 2018
          </a>
        </li>
        <li>
          <a
            class="list-group-item list-group-item-action"
            href="https://courses.edx.org/certificates/4dd64d88a9104903830cb799b05a0823"
            target="_blank"
            >Verified Certificate of CSS Basics- Microsoft, edX - 2018
          </a>
        </li>
        <li>
          <a
            class="list-group-item list-group-item-action"
            href="https://courses.edx.org/certificates/9994a3b65ae7469fbc952e0940ae2c13"
            target="_blank"
            >Verified Certificate of HTML5 and CSS Fundamentals - Microsoft,
            W3C, edX - 2018
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>
```

## scss
```scss
div.about-section {
  background: rgba($color: lightgrey, $alpha: 0.3);
  border-radius: 10px;
  position: relative;
  width: 1024px;
  height: 900px;
  // to make the other component stay in the center
  left: 0;
  top: 10px;
  right: 0;
  bottom: 0;
  margin: 0 auto;
}

div.photo {
  margin: 20px;
  height: 100%;
  width: 100%;
  position: relative;
}

img {
  height: 150px;
  position: absolute;
  top: 50%;
  left: 50%;
  margin-top: -65px;
  margin-left: -35px;
  border-radius: 20px;
}

div.certificate,
p {
  margin: 50px;
}
```

**Comment by puddlejumper26** [comment]
## SCSS 
in order to minimize the code, this time is focusing on the settings of height and width, try to use the nature of element it self, rather than setting numbers. 

```scss
html, body {
  height: 100%;
}

div.about-section {
  background: rgba($color: lightgrey, $alpha: 0.3);
  border: 1px solid skyblue;
  border-radius: 2px;
  box-shadow: 0 20px 30px rgba(7, 1, 1, 1);
  color: cyan;
  height:950px;
  position: relative;
  width: 1024px;
  // to make the other component stay in the center
  left: 0;
  top: 10px;
  right: 0;
  bottom: 10px;
  margin: 0 auto;
}

div.photo {
  margin: 60px 40px 40px 40px;
  position: relative;
}

img {
  border: 1px solid cyan;
  box-shadow: 15px 15px 15px rgba(0, 0, 0, 0.5);
  height: 150px;
  position: absolute;
  top: 50%;
  left: 50%;
  margin-top: -65px;
  margin-left: -35px;
}

div.certificate,
p {
  margin: 50px;
}

span, a {
  color: cyan;
}

span { margin-right: 20px;}

/*Moving blue chips*/
#wrap {
  display: flex;
  justify-content: center;
}
#wrap div {
  background-color: cyan;
  border-radius: 10%;
  float: left;
  height: 30px;
  margin-left: 10px;
  width: 4px;
  -webkit-animation: fadeOut 3s infinite ease-in-out;
}

@-webkit-keyframes fadeOut {
  0%,
  80%,
  100% {
    -webkit-transform: scaleY(0.4);
  }
  20% {
    -webkit-transform: scaleY(1);
  }
}

#wrap .line1 {
  -webkit-animation-delay: -0.9s;
}
#wrap .line2 {
  -webkit-animation-delay: -0.8s;
}
#wrap .line3 {
  -webkit-animation-delay: -0.7s;
}
#wrap .line4 {
  -webkit-animation-delay: -0.8s;
}
#wrap .line5 {
  -webkit-animation-delay: -0.9s;
}

```
